server:
  port: 8761
  evictionIntervalTimerInMs: 5000
spring:
  application:
    name: register-center
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:${server.port}/eureka/
  instance:
    hostname: localhost